export const MOBILE_PATHS = {
  login: '/mobile/auth/login',
  session: '/mobile/auth/session',
  logout: '/mobile/auth/logout',
  twoFactorStatus: '/mobile/auth/two-factor/status',
  twoFactorVerify: '/mobile/auth/two-factor/verify',
  passwordReset: '/mobile/auth/password-reset/request',
  bootstrap: '/mobile/bootstrap',
  dashboard: '/mobile/dashboard',
  classes: '/mobile/classes',
  classDetails: (id: string) => `/mobile/classes/${encodeURIComponent(id)}`,
  catechumens: '/mobile/catechumens',
  catechumenDetails: (id: string) => `/mobile/catechumens/${encodeURIComponent(id)}`,
  families: '/mobile/families',
  familyDetails: (id: string) => `/mobile/families/${encodeURIComponent(id)}`,
  meetings: '/mobile/meetings',
  meetingDetails: (id: string) => `/mobile/meetings/${encodeURIComponent(id)}`,
  attendance: '/mobile/attendance',
  messages: '/mobile/messages',
  messageDetails: (id: string) => `/mobile/messages/${encodeURIComponent(id)}`,
  conversationContacts: '/mobile/messages/contacts',
  conversations: '/mobile/messages/conversations',
  notifications: '/mobile/notifications',
  notificationRead: (id: string) => `/mobile/notifications/${encodeURIComponent(id)}/read`,
  notificationsReadAll: '/mobile/notifications/read-all',
  documents: '/mobile/documents',
  document: (id: string) => `/mobile/documents/${encodeURIComponent(id)}`,
  socialFeed: '/mobile/social/feed',
  socialAccess: '/mobile/social/access',
  socialTopics: '/mobile/social/topics',
  socialPosts: '/mobile/social/posts',
  socialProfile: (handle: string) => `/mobile/social/profile/${encodeURIComponent(handle)}`,
  socialMe: '/mobile/social/me',
  socialProfileUpdate: '/mobile/social/profile',
  socialFollow: '/mobile/social/follow',
  socialBlock: '/mobile/social/block',
  socialSharePreview: '/mobile/social/share/preview',
  socialPost: (slug: string) => `/mobile/social/posts/${encodeURIComponent(slug)}`,
  socialComments: '/mobile/social/comments',
  socialReact: '/mobile/social/react',
  socialSearch: '/mobile/social/search',
  socialPulse: '/mobile/social/pulse',
  socialConnections: '/mobile/social/connections',
  socialBlocks: '/mobile/social/blocks',
  socialReport: '/mobile/social/report',
  socialImageUpload: '/mobile/social/images',
  socialVideoUpload: '/mobile/social/videos',
  profileAvatarUpload: '/mobile/profile/avatar',
  pushToken: '/mobile/push-token',
  // Fase B — operação da catequese
  classAttendanceMatrix: (id: string) => `/mobile/classes/${encodeURIComponent(id)}/attendance`,
  classPlan: (id: string) => `/mobile/classes/${encodeURIComponent(id)}/plan`,
  classChat: (id: string) => `/mobile/classes/${encodeURIComponent(id)}/chat`,
  classEnrollments: (id: string) => `/mobile/classes/${encodeURIComponent(id)}/enrollments`,
  classEnrollment: (id: string, enrollmentId: string) =>
    `/mobile/classes/${encodeURIComponent(id)}/enrollments/${encodeURIComponent(enrollmentId)}`,
  classCatechists: (id: string) => `/mobile/classes/${encodeURIComponent(id)}/catechists`,
  classCatechist: (id: string, userId: string) =>
    `/mobile/classes/${encodeURIComponent(id)}/catechists/${encodeURIComponent(userId)}`,
  communities: '/mobile/communities',
  catechists: '/mobile/catechists',
  attendanceBatch: '/mobile/attendance/batch',
  attendanceJustify: '/mobile/attendance/justify',
  meetingAttendance: (id: string) => `/mobile/meetings/${encodeURIComponent(id)}/attendance`,
  meetingSheet: (id: string) => `/mobile/meetings/${encodeURIComponent(id)}/sheet`,
  meetingJustify: (id: string) => `/mobile/meetings/${encodeURIComponent(id)}/justify`,
  catechumenAttendanceReport: (id: string) => `/mobile/catechumens/${encodeURIComponent(id)}/attendance-report`,
  catechumenUploadToken: (id: string) => `/mobile/catechumens/${encodeURIComponent(id)}/upload-token`,
  familyGuardians: (id: string) => `/mobile/families/${encodeURIComponent(id)}/guardians`,
  familyGuardian: (id: string, guardianId: string) =>
    `/mobile/families/${encodeURIComponent(id)}/guardians/${encodeURIComponent(guardianId)}`,
  consents: '/mobile/consents',
  // Fase C — comunicação
  conversationRead: (id: string) => `/mobile/messages/${encodeURIComponent(id)}/read`,
  conversationMute: (id: string) => `/mobile/messages/${encodeURIComponent(id)}/mute`,
  conversationParticipant: (id: string, userId: string) =>
    `/mobile/messages/${encodeURIComponent(id)}/participants/${encodeURIComponent(userId)}`,
  socialPostDelete: (id: string) => `/mobile/social/posts/${encodeURIComponent(id)}`,
  socialCommentDelete: (id: string) => `/mobile/social/comments/${encodeURIComponent(id)}`,
  socialShare: '/mobile/social/share',
  socialWatch: '/mobile/social/watch',
  socialFollowState: '/mobile/social/follow-state',
  dashboardFocus: '/mobile/dashboard/focus',
  announcements: '/mobile/announcements',
  announcementAck: (id: string) => `/mobile/announcements/${encodeURIComponent(id)}/ack`,
  birthdays: '/mobile/birthdays',
  birthdayGift: '/mobile/birthdays/gift',
  globalSearch: '/mobile/search',
  // Fase D — conteúdo
  bibleSearch: '/mobile/bible/search',
  catechismSearch: '/mobile/catechism/search',
  catechismCategory: (category: string) => `/mobile/catechism/category/${encodeURIComponent(category)}`,
  catechismEntry: (number: number) => `/mobile/catechism/entries/${number}`,
  directorySearch: '/mobile/directory/search',
  directoryPart: (part: string) => `/mobile/directory/part/${encodeURIComponent(part)}`,
  directoryEntry: (number: number) => `/mobile/directory/entries/${number}`,
  content: '/mobile/content',
  contentDetails: (id: string) => `/mobile/content/${encodeURIComponent(id)}`,
  contentStatus: (id: string) => `/mobile/content/${encodeURIComponent(id)}/status`,
  calendarEvents: '/mobile/calendar/events',
  documentsUpload: '/mobile/documents/upload',
  documentVerify: (id: string) => `/mobile/documents/${encodeURIComponent(id)}/verify`,
  documentReject: (id: string) => `/mobile/documents/${encodeURIComponent(id)}/reject`,
  announcementPublish: (id: string) => `/mobile/announcements/${encodeURIComponent(id)}/publish`,
  // Fase E — gestão e conta
  team: '/mobile/team',
  teamInvite: '/mobile/team/invite',
  teamInviteResend: '/mobile/team/invite/resend',
  teamInviteCancel: '/mobile/team/invite/cancel',
  teamMember: (membershipId: string) => `/mobile/team/members/${encodeURIComponent(membershipId)}`,
  teamMemberRole: (membershipId: string) => `/mobile/team/members/${encodeURIComponent(membershipId)}/role`,
  teamMemberClasses: (membershipId: string) => `/mobile/team/members/${encodeURIComponent(membershipId)}/classes`,
  familyInvites: '/mobile/team/family-invites',
  invitationAccept: '/mobile/invitations/accept',
  reportsOverview: '/mobile/reports/overview',
  classReport: (id: string) => `/mobile/reports/classes/${encodeURIComponent(id)}`,
  profile: '/mobile/profile',
  profilePassword: '/mobile/profile/password',
  emailPreferences: '/mobile/profile/email-preferences',
  dataExport: '/mobile/profile/data-export',
  twoFactor: '/mobile/profile/two-factor',
  twoFactorStart: '/mobile/profile/two-factor/start',
  twoFactorVerifySetup: '/mobile/profile/two-factor/verify',
  twoFactorDisable: '/mobile/profile/two-factor/disable',
  groups: '/mobile/groups',
  groupJoin: (id: string) => `/mobile/groups/${encodeURIComponent(id)}/join`,
  groupLeave: (id: string) => `/mobile/groups/${encodeURIComponent(id)}/leave`,
  formation: '/mobile/formation',
  formationEnroll: (id: string) => `/mobile/formation/${encodeURIComponent(id)}/enroll`,
  formationUnenroll: (id: string) => `/mobile/formation/${encodeURIComponent(id)}/unenroll`,
  sacraments: '/mobile/sacraments',
  sacrament: (id: string) => `/mobile/sacraments/${encodeURIComponent(id)}`,
  support: '/mobile/support',
  bibleBooks: '/mobile/bible/books',
  bibleBook: (id: string) => `/mobile/bible/books/${encodeURIComponent(id)}`,
  bibleChapter: (bookId: string, chapter: number) =>
    `/mobile/bible/books/${encodeURIComponent(bookId)}/chapters/${chapter}`,
} as const;

export const APP_TABS = [
  { name: 'index', href: '/(app)/(tabs)', label: 'Início', icon: 'home-outline' },
  { name: 'community', href: '/(app)/(tabs)/community', label: 'Comunidade', shortLabel: 'Rede', icon: 'people-outline' },
  { name: 'classes', href: '/(app)/(tabs)/classes', label: 'Turmas', icon: 'school-outline' },
  { name: 'messages', href: '/(app)/(tabs)/messages', label: 'Mensagens', shortLabel: 'Chat', icon: 'chatbubble-outline' },
  { name: 'more', href: '/(app)/(tabs)/more', label: 'Mais', icon: 'ellipsis-horizontal' },
] as const;
