export const MOBILE_PATHS = {
  login: '/mobile/auth/login',
  session: '/mobile/auth/session',
  logout: '/mobile/auth/logout',
  twoFactorStatus: '/mobile/auth/two-factor/status',
  twoFactorVerify: '/mobile/auth/two-factor/verify',
  passwordReset: '/mobile/auth/password-reset/request',
  bootstrap: '/mobile/bootstrap',
  dashboard: '/mobile/dashboard',
  classes: '/mobile/classes',
  classDetails: (id: string) => `/mobile/classes/${encodeURIComponent(id)}`,
  catechumens: '/mobile/catechumens',
  catechumenDetails: (id: string) => `/mobile/catechumens/${encodeURIComponent(id)}`,
  families: '/mobile/families',
  familyDetails: (id: string) => `/mobile/families/${encodeURIComponent(id)}`,
  meetings: '/mobile/meetings',
  meetingDetails: (id: string) => `/mobile/meetings/${encodeURIComponent(id)}`,
  attendance: '/mobile/attendance',
  messages: '/mobile/messages',
  messageDetails: (id: string) => `/mobile/messages/${encodeURIComponent(id)}`,
  notifications: '/mobile/notifications',
  notificationRead: (id: string) => `/mobile/notifications/${encodeURIComponent(id)}/read`,
  notificationsReadAll: '/mobile/notifications/read-all',
  documents: '/mobile/documents',
  document: (id: string) => `/mobile/documents/${encodeURIComponent(id)}`,
  socialFeed: '/mobile/social/feed',
  socialAccess: '/mobile/social/access',
  socialTopics: '/mobile/social/topics',
  socialPosts: '/mobile/social/posts',
  socialProfile: (handle: string) => `/mobile/social/profile/${encodeURIComponent(handle)}`,
  socialMe: '/mobile/social/me',
  socialProfileUpdate: '/mobile/social/profile',
  socialFollow: '/mobile/social/follow',
  socialBlock: '/mobile/social/block',
  socialSharePreview: '/mobile/social/share/preview',
  socialPost: (slug: string) => `/mobile/social/posts/${encodeURIComponent(slug)}`,
  socialComments: '/mobile/social/comments',
  socialReact: '/mobile/social/react',
  socialSearch: '/mobile/social/search',
  socialPulse: '/mobile/social/pulse',
  socialConnections: '/mobile/social/connections',
  socialBlocks: '/mobile/social/blocks',
  socialReport: '/mobile/social/report',
  bibleBooks: '/mobile/bible/books',
  bibleBook: (id: string) => `/mobile/bible/books/${encodeURIComponent(id)}`,
  bibleChapter: (bookId: string, chapter: number) =>
    `/mobile/bible/books/${encodeURIComponent(bookId)}/chapters/${chapter}`,
  calendar: '/mobile/calendar',
  announcements: '/mobile/announcements',
  announcementDetails: (id: string) => `/mobile/announcements/${encodeURIComponent(id)}`,
  acknowledgeAnnouncement: (id: string) => `/mobile/announcements/${encodeURIComponent(id)}/acknowledge`,
  journeys: '/mobile/journeys',
  journeyDetails: (id: string) => `/mobile/journeys/${encodeURIComponent(id)}`,
  journeyMilestone: (id: string) => `/mobile/journeys/milestones/${encodeURIComponent(id)}`,
  catechismSearch: '/mobile/catechism/search',
  catechismCategory: (category: string) =>
    `/mobile/catechism/categories/${encodeURIComponent(category)}`,
  catechismEntry: (number: number) => `/mobile/catechism/entries/${number}`,
} as const;

export const APP_TABS = [
  { name: 'index', href: '/(app)/(tabs)', label: 'Início', icon: 'home' },
  { name: 'community', href: '/(app)/(tabs)/community', label: 'Comunidade', icon: 'users' },
  { name: 'classes', href: '/(app)/(tabs)/classes', label: 'Turmas', icon: 'book-open' },
  { name: 'messages', href: '/(app)/(tabs)/messages', label: 'Mensagens', icon: 'message-circle' },
  { name: 'more', href: '/(app)/(tabs)/more', label: 'Mais', icon: 'menu' },
] as const;
