export const MOBILE_PATHS = {
  login: '/mobile/auth/login',
  signup: '/mobile/auth/signup',
  session: '/mobile/auth/session',
  logout: '/mobile/auth/logout',
  twoFactorStatus: '/mobile/auth/two-factor/status',
  twoFactorVerify: '/mobile/auth/two-factor/verify',
  twoFactorSetupStart: '/mobile/settings/2fa/start',
  twoFactorSetupVerify: '/mobile/settings/2fa/verify',
  twoFactorDisable: '/mobile/settings/2fa/disable',
  passwordReset: '/mobile/auth/password-reset/request',
  webBridge: '/mobile/auth/web-bridge',
  bootstrap: '/mobile/bootstrap',
  dashboard: '/mobile/dashboard',
  classes: '/mobile/classes',
  classDetails: (id: string) => `/mobile/classes/${encodeURIComponent(id)}`,
  catechumens: '/mobile/catechumens',
  catechumenDetails: (id: string) => `/mobile/catechumens/${encodeURIComponent(id)}`,
  families: '/mobile/families',
  familyDetails: (id: string) => `/mobile/families/${encodeURIComponent(id)}`,
  meetings: '/mobile/meetings',
  meetingDetails: (id: string) => `/mobile/meetings/${encodeURIComponent(id)}`,
  attendance: '/mobile/attendance',
  messages: '/mobile/messages',
  conversations: '/mobile/conversations',
  messageDetails: (id: string) => `/mobile/messages/${encodeURIComponent(id)}`,
  notifications: '/mobile/notifications',
  notificationRead: (id: string) => `/mobile/notifications/${encodeURIComponent(id)}/read`,
  notificationsReadAll: '/mobile/notifications/read-all',
  documents: '/mobile/documents',
  document: (id: string) => `/mobile/documents/${encodeURIComponent(id)}`,
  documentUpload: '/mobile/documents/upload',
  calendar: '/mobile/calendar',
  calendarEvent: (id: string) => `/mobile/calendar/${encodeURIComponent(id)}`,
  announcements: '/mobile/announcements',
  announcementAck: (id: string) => `/mobile/announcements/${encodeURIComponent(id)}/acknowledge`,
  groups: '/mobile/groups',
  groupDetails: (id: string) => `/mobile/groups/${encodeURIComponent(id)}`,
  groupJoin: (id: string) => `/mobile/groups/${encodeURIComponent(id)}/join`,
  groupLeave: (id: string) => `/mobile/groups/${encodeURIComponent(id)}/leave`,
  groupNotices: (id: string) => `/mobile/groups/${encodeURIComponent(id)}/notices`,
  team: '/mobile/team',
  teamInvite: '/mobile/team/invite',
  familyInvites: '/mobile/family-invites',
  contentLibrary: '/mobile/content-library',
  officialLibrary: '/mobile/official-library',
  catechism: '/mobile/catechism',
  catechismEntry: (number: number) => `/mobile/catechism/${number}`,
  directory: '/mobile/directory',
  directoryEntry: (number: number) => `/mobile/directory/${number}`,
  journeys: '/mobile/journeys',
  journeyTemplates: '/mobile/journey-templates',
  parishes: '/mobile/parishes',
  communities: '/mobile/communities',
  reports: '/mobile/reports',
  catecheticalYears: '/mobile/catechetical-years',
  formation: '/mobile/formation',
  birthdays: '/mobile/birthdays',
  settingsProfile: '/mobile/settings/profile',
  settingsPassword: '/mobile/settings/password',
  emailPrefs: '/mobile/settings/email-prefs',
  consents: '/mobile/consents',
  onboardingCoordinator: '/mobile/onboarding/coordinator',
  onboardingMember: '/mobile/onboarding/member',
  socialFeed: '/mobile/social/feed',
  socialAccess: '/mobile/social/access',
  socialTopics: '/mobile/social/topics',
  socialPosts: '/mobile/social/posts',
  socialProfile: (handle: string) => `/mobile/social/profile/${encodeURIComponent(handle)}`,
  socialMe: '/mobile/social/me',
  socialProfileUpdate: '/mobile/social/profile',
  socialFollow: '/mobile/social/follow',
  socialBlock: '/mobile/social/block',
  socialSharePreview: '/mobile/social/share/preview',
  socialPost: (slug: string) => `/mobile/social/posts/${encodeURIComponent(slug)}`,
  socialComments: '/mobile/social/comments',
  socialReact: '/mobile/social/react',
  socialSearch: '/mobile/social/search',
  socialPulse: '/mobile/social/pulse',
  socialConnections: '/mobile/social/connections',
  socialBlocks: '/mobile/social/blocks',
  socialReport: '/mobile/social/report',
  bibleBooks: '/mobile/bible/books',
  bibleBook: (id: string) => `/mobile/bible/books/${encodeURIComponent(id)}`,
  bibleChapter: (bookId: string, chapter: number) =>
    `/mobile/bible/books/${encodeURIComponent(bookId)}/chapters/${chapter}`,
} as const;

export const TAB_FILES = [
  { name: 'index', iconKey: 'dashboard' },
  { name: 'community', iconKey: 'community' },
  { name: 'classes', iconKey: 'classes' },
  { name: 'calendar', iconKey: 'calendar' },
  { name: 'messages', iconKey: 'messages' },
  { name: 'groups', iconKey: 'groups' },
  { name: 'bible-tab', iconKey: 'bible' },
  { name: 'more', iconKey: 'more' },
] as const;

/** @deprecated Use role-aware tabs from getVisibleNavigation */
export const APP_TABS = [
  { name: 'index', href: '/(app)/(tabs)', label: 'Início', icon: 'home-outline' },
  { name: 'community', href: '/(app)/(tabs)/community', label: 'Comunidade', icon: 'people-outline' },
  { name: 'classes', href: '/(app)/(tabs)/classes', label: 'Turmas', icon: 'school-outline' },
  { name: 'calendar', href: '/(app)/(tabs)/calendar', label: 'Agenda', icon: 'calendar-outline' },
  { name: 'messages', href: '/(app)/(tabs)/messages', label: 'Mensagens', icon: 'chatbubble-outline' },
  { name: 'more', href: '/(app)/(tabs)/more', label: 'Mais', icon: 'ellipsis-horizontal' },
] as const;
