-- Rename MISSIONARY_FREE to CATECHIST_FREE
ALTER TYPE "BillingPlan" RENAME VALUE 'MISSIONARY_FREE' TO 'CATECHIST_FREE';

-- Add new CATECHIST_PRO plan
ALTER TYPE "BillingPlan" ADD VALUE 'CATECHIST_PRO';
