export const copy = {
  brand: 'Catequese Viva',
  common: {
    loading: 'Carregando…',
    back: 'Voltar',
    open: 'Abrir',
    save: 'Salvar',
    saving: 'Salvando…',
    send: 'Enviar',
    sending: 'Enviando…',
    cancel: 'Cancelar',
    confirm: 'Confirmar',
    all: 'Todos',
    peopleCount: (n: number) => (n === 1 ? '1 pessoa' : `${n} pessoas`),
    errorLoad: (area: string) => `Não foi possível carregar ${area}.`,
  },
  auth: {
    loginTitle: 'Entrar',
    loginSubtitle: 'Use a mesma conta da plataforma web. A sessão fica guardada neste celular.',
    loginTestHint: 'Ambiente de teste: toque em Entrar com a conta já preenchida. Senha Teste@123 (T maiúsculo).',
    email: 'E-mail',
    emailPlaceholder: 'voce@paroquia.com',
    password: 'Senha',
    passwordPlaceholder: 'Sua senha',
    submit: 'Entrar',
    submitting: 'Entrando…',
    forgot: 'Esqueceu a senha?',
    loginError: 'Não foi possível entrar.',
    loginInvalid: 'E-mail ou senha incorretos.',
    loginInvalidDev: 'E-mail ou senha incorretos. Use catequista.lead@catequese.com e senha Teste@123 (T maiúsculo). Esta base local não aceita a conta de produção.',
    twoFactorTitle: 'Verificação em dois passos',
    twoFactorSubtitle: 'Digite o código de 6 dígitos do aplicativo autenticador.',
    code: 'Código',
    continue: 'Continuar',
    verifying: 'Verificando…',
    leave: 'Sair',
    recoverTitle: 'Recuperar acesso',
    recoverSubtitle: 'Enviamos um link se o e-mail existir na Catequese Viva.',
    recoverSent: 'Se a conta existir, o e-mail já foi enviado.',
    sendLink: 'Enviar link',
    backToLogin: 'Voltar ao início de sessão',
    createAccount: 'Criar conta',
  },
  tabs: {
    home: 'Início',
    community: 'Comunidade',
    classes: 'Turmas',
    calendar: 'Agenda',
    messages: 'Mensagens',
    groups: 'Grupos',
    bible: 'Bíblia',
    more: 'Mais',
  },
  home: {
    hello: (name: string) => `Olá, ${name}`,
    kicker: 'Catequese Viva',
    subtitle: 'O essencial da catequese, no bolso.',
    today: 'Hoje na catequese',
    classes: 'Turmas',
    catechumens: 'Catequizandos',
    attendance: 'Presença',
    notifications: 'Notificações',
    notificationsUnread: (n: number) => `Notificações (${n})`,
    goCommunity: 'Ir à Comunidade',
    announcements: 'Avisos pastorais',
    birthdays: 'Aniversários',
    calendar: 'Agenda',
    upcoming: 'Próximos encontros',
    nextMeeting: 'Próximo encontro',
    emptyTitle: 'Sem encontros à vista',
    emptyBody: 'Quando houver um encontro marcado, aparece aqui.',
    errorTitle: 'Não foi possível carregar o início',
    meetingFallback: 'Encontro',
    classFallback: 'Turma',
  },
  signup: {
    title: 'Criar conta',
    subtitle: 'A mesma conta da plataforma web. Depois confirme o e-mail se o servidor pedir.',
    firstName: 'Nome',
    lastName: 'Apelido',
    submit: 'Criar conta',
    submitting: 'A criar…',
    haveAccount: 'Já tenho conta',
    error: 'Não foi possível criar a conta.',
  },
  onboarding: {
    title: 'Começar',
    subtitle: 'Diga-nos como quer organizar a catequese neste espaço.',
    parishName: 'Nome da paróquia ou grupo',
    city: 'Cidade',
    state: 'UF',
    yearName: 'Ano catequético',
    yearStart: 'Início',
    yearEnd: 'Fim',
    className: 'Primeira turma (opcional)',
    skipClass: 'Saltar turma por agora',
    submit: 'Concluir',
    memberTitle: 'Como vai usar a Catequese Viva?',
    member: 'Sou membro / catequizando',
    organizer: 'Organizo um grupo',
    catechesis: 'Coordeno catequese',
  },
  community: {
    title: 'Comunidade',
    subtitle: 'Ler e seguir é livre. Publicar pede assinatura.',
    sorts: {
      recent: 'Recentes',
      trending: 'Em alta',
      foryou: 'Para você',
    },
    followingChip: 'Quem eu sigo',
    followingOn: 'Vendo quem você segue',
    followingOff: 'Só quem você segue',
    searchPeople: 'Pesquisar pessoas e publicações',
    subscribeBanner: 'Você pode ler e seguir. Para publicar, precisa de uma assinatura ativa.',
    limitedBanner: 'A publicação está limitada nesta conta.',
    compose: 'Nova publicação',
    posts: 'Publicações',
    shortcuts: 'Atalhos da Comunidade',
    emptyTitle: 'Ainda não há publicações',
    emptyBody: 'Quando a Comunidade tiver mensagens, elas aparecem aqui.',
    errorTitle: 'Não foi possível carregar a Comunidade',
    followingTitle: 'Quem você segue',
    followingSubtitle: 'Só publicações de quem você segue.',
    shortsTitle: 'Vídeos curtos',
    shortsSubtitle: 'Clipes da Comunidade — o Rhema no celular.',
  },
  compose: {
    title: 'Nova publicação',
    checking: 'Verificando se a sua conta pode publicar…',
    canPublish: 'Compartilhe um momento ou um versículo com a Comunidade.',
    needsSub: 'A publicação exige assinatura.',
    body: 'Texto',
    bodyPlaceholder: 'Escreva com paz e clareza…',
    shareKind: 'Tipo de partilha (opcional)',
    shareId: 'ID da fonte (ex. bookId:capítulo:versículo)',
    previewShare: 'Pré-visualizar partilha',
    includeVerse: 'Incluir um versículo da Bíblia',
    publish: 'Publicar',
    publishing: 'Publicando…',
    published: 'Publicado',
    invalidShare: 'Não foi possível preparar o versículo.',
    error: 'Não foi possível publicar.',
  },
  post: {
    title: 'Publicação',
    open: 'Abrir publicação',
    more: 'Ver mais',
    less: 'Ver menos',
    meta: (reactions: number, comments: number) =>
      `${reactions} ${reactions === 1 ? 'reação' : 'reações'} · ${comments} ${comments === 1 ? 'comentário' : 'comentários'}`,
    reactions: {
      AMEM: 'Amém',
      REZO: 'Rezo',
      ALELUIA: 'Aleluia',
    },
    comments: 'Comentários',
    commentsEmptyTitle: 'Ainda sem comentários',
    commentsEmptyBody: 'Seja o primeiro a responder com um Amém ou uma palavra.',
    commentsNeedAccount: 'Comentários pedem a mesma conta com que você lê a Comunidade.',
    yourComment: 'Seu comentário',
    commentPlaceholder: 'Uma palavra de fé…',
    comment: 'Comentar',
    report: 'Denunciar',
    reportReasons: {
      DOCTRINE: 'Doutrina',
      HATE: 'Ódio',
      SPAM: 'Indesejado',
      OTHER: 'Outro',
    },
    sendReport: 'Enviar denúncia',
    reportSent: 'Denúncia enviada. Obrigado.',
    reportError: 'Não foi possível denunciar.',
    errorTitle: 'Não foi possível carregar a publicação',
    notFound: 'Esta publicação não foi encontrada.',
  },
  profile: {
    noHandle: 'Sem nome público',
    followers: (n: number) => `${n} seguidores`,
    following: (n: number) => `${n} seguindo`,
    ownHint: 'Este é o seu perfil público.',
    edit: 'Editar perfil',
    follow: 'Seguir',
    followingState: 'Seguindo',
    block: 'Bloquear',
    unblock: 'Desbloquear',
    blockConfirmTitle: 'Bloquear esta conta?',
    blockConfirmBody: (handle: string) =>
      `As publicações de ${handle} deixam de aparecer na Comunidade.`,
    posts: 'Publicações',
    emptyPostsTitle: 'Ainda sem publicações',
    emptyPostsBody: 'Quando este perfil publicar, as mensagens aparecem aqui.',
    errorTitle: 'Não foi possível carregar o perfil',
    notFound: 'Este nome público não foi encontrado.',
  },
  editProfile: {
    title: 'Editar perfil',
    subtitle: 'O nome público e a bio aparecem no seu cartão da Comunidade.',
    handle: 'Seu @',
    handlePlaceholder: 'catequista',
    bio: 'Bio',
    bioPlaceholder: 'Uma linha sobre o seu serviço na catequese.',
    website: 'Site (opcional)',
    save: 'Salvar perfil público',
    saved: 'Perfil salvo',
    viewProfile: 'Ver o meu perfil',
    blocked: 'Contas bloqueadas',
    error: 'Não foi possível salvar.',
  },
  search: {
    title: 'Pesquisar',
    subtitle: 'Encontre catequistas, tópicos e publicações da Comunidade.',
    label: 'Pesquisar',
    placeholder: 'Nome, @ ou uma palavra',
    hint: 'Escreva pelo menos 2 letras.',
    emptyTitle: 'Nada encontrado',
    emptyBody: 'Tente um @, um nome ou uma palavra da publicação.',
    people: 'Pessoas',
    posts: 'Publicações',
    errorTitle: 'Não foi possível pesquisar',
  },
  people: {
    membersTitle: 'Membros',
    membersSubtitle: (n: number) => `${n} pessoas já publicaram na Comunidade.`,
    membersEmptyTitle: 'Ainda sem membros visíveis',
    membersEmptyBody: 'Quando houver publicações, os autores aparecem aqui.',
    blockedTitle: 'Bloqueados',
    blockedSubtitle: 'Estas contas não aparecem no seu feed nem conseguem seguir você.',
    blockedEmptyTitle: 'Ninguém bloqueado',
    blockedEmptyBody: 'Quando bloquear alguém, a conta fica nesta lista.',
    followers: 'Seguidores',
    following: 'Seguindo',
    emptyFollowing: 'Ainda não segue ninguém',
    emptyFollowers: 'Ainda sem seguidores',
    emptyConnections: 'Quando houver ligações, elas aparecem aqui.',
    errorTitle: 'Não foi possível carregar a lista',
    catechumensTitle: 'Catequizandos',
    catechumensSubtitle: 'Fichas da turma e da família.',
    catechumensEmpty: 'Ainda sem catequizandos neste espaço.',
    newCatechumen: 'Novo catequizando',
    firstName: 'Nome',
    lastName: 'Apelido',
    familiesTitle: 'Famílias',
    familiesEmpty: 'Ainda sem famílias neste espaço.',
    newFamily: 'Nova família',
    familyName: 'Nome da família',
    teamTitle: 'Equipa',
    teamEmpty: 'Ninguém na equipa ainda.',
    invitesTitle: 'Convites da família',
    invitesEmpty: 'Sem convites pendentes.',
    inviteEmail: 'E-mail',
    inviteRole: 'Papel',
    sendInvite: 'Enviar convite',
    importCsv: 'Importar CSV',
    create: 'Criar',
    created: 'Guardado',
  },
  topics: {
    title: 'Tópicos',
    subtitle: 'As áreas temáticas da Comunidade — toque para abrir o feed.',
    emptyTitle: 'Ainda sem tópicos',
    emptyBody: 'Quando a Comunidade tiver temas ativos, eles aparecem aqui.',
    posts: (n: number) => (n === 1 ? '1 publicação' : `${n} publicações`),
    errorTitle: 'Não foi possível carregar os tópicos',
  },
  classes: {
    title: 'Turmas',
    subtitle: 'Encontros, catequizandos e presença.',
    emptyTitle: 'Sem turmas',
    emptyBody: 'Quando você pertencer a uma turma, ela aparece aqui.',
    errorTitle: 'Não foi possível carregar as turmas',
    fallback: 'Turma',
    community: 'Comunidade',
    meetings: 'Encontros',
    emptyMeetingsTitle: 'Sem encontros',
    emptyMeetingsBody: 'Esta turma ainda não tem encontros listados.',
    classError: 'Não foi possível carregar a turma',
  },
  meeting: {
    fallback: 'Encontro',
    markAttendance: 'Marcar presença',
    errorTitle: 'Não foi possível carregar o encontro',
    notFound: 'Não encontrado.',
  },
  attendance: {
    title: 'Presença',
    subtitle: 'Toque no estado e grave cada catequizando.',
    catechumen: 'Catequizando',
    status: 'Estado',
    save: 'Gravar',
    saving: 'Gravando…',
    saved: 'Presença gravada',
    emptyTitle: 'Sem lista',
    emptyBody: 'Este encontro ainda não tem catequizandos para marcar.',
    errorTitle: 'Não foi possível carregar a presença',
    saveError: 'Não foi possível gravar.',
    statuses: {
      PRESENT: 'Presente',
      ABSENT: 'Falta',
      LATE: 'Atraso',
      EXCUSED: 'Justificado',
    },
  },
  messages: {
    title: 'Mensagens',
    subtitle: 'Conversas da paróquia e das turmas.',
    emptyTitle: 'Caixa vazia',
    emptyBody: 'Quando alguém escrever, a conversa aparece aqui.',
    errorTitle: 'Não foi possível carregar as mensagens',
    fallback: 'Conversa',
    threadError: 'Não foi possível carregar a conversa',
    member: 'Membro',
    field: 'Mensagem',
    placeholder: 'Escreva uma mensagem…',
    new: 'Nova conversa',
    pickMember: 'Escolha alguém da equipa para começar.',
  },
  notifications: {
    title: 'Notificações',
    emptyTitle: 'Tudo em dia',
    emptyBody: 'Não há notificações por ler.',
    markRead: 'Marcar como lida',
    markAll: 'Marcar todas como lidas',
    fallback: 'Aviso',
    errorTitle: 'Não foi possível carregar as notificações',
  },
  documents: {
    title: 'Documentos',
    subtitle: 'Arquivos da família e da turma.',
    emptyTitle: 'Pasta vazia',
    emptyBody: 'Ainda não há documentos para mostrar.',
    errorTitle: 'Não foi possível carregar os documentos',
    fallback: 'Documento',
    upload: 'Enviar documento',
    uploading: 'A enviar…',
    uploaded: 'Documento enviado',
    type: 'Tipo',
    types: {
      BAPTISM_CERTIFICATE: 'Batismo',
      BIRTH_CERTIFICATE: 'Nascimento',
      CONSENT_FORM: 'Consentimento',
      MARRIAGE_CERTIFICATE: 'Matrimónio',
      PASTORAL_LETTER: 'Carta pastoral',
      OTHER: 'Outro',
    },
  },
  bible: {
    title: 'Bíblia',
    subtitle: 'Leia e compartilhe um versículo na Comunidade.',
    book: 'Livro',
    chapter: (n: number) => `Capítulo ${n}`,
    share: 'Compartilhar na Comunidade',
    emptyChaptersTitle: 'Sem capítulos',
    emptyChaptersBody: 'Este livro ainda não tem capítulos guardados.',
    errorBible: 'Não foi possível carregar a Bíblia',
    errorBook: 'Não foi possível carregar o livro',
    errorChapter: 'Não foi possível carregar o capítulo',
  },
  more: {
    title: 'Mais',
    bible: 'Bíblia',
    documents: 'Documentos',
    communityAreas: 'Áreas da Comunidade',
    viewProfile: (handle: string) => `Ver perfil @${handle}`,
    editProfile: 'Editar perfil público',
    saveProfile: 'Guardar perfil público',
    workspace: 'Espaço de trabalho',
    logout: 'Encerrar sessão',
    logoutTitle: 'Encerrar sessão?',
    logoutBody: 'Você vai sair deste celular. Pode entrar de novo quando quiser.',
    openWeb: 'Abrir no navegador',
  },
  calendar: {
    title: 'Agenda',
    subtitle: 'Encontros e datas litúrgicas.',
    emptyTitle: 'Agenda livre',
    emptyBody: 'Quando houver um encontro ou festa, aparece aqui.',
    newEvent: 'Novo evento',
    eventName: 'Nome',
    eventDate: 'Data (AAAA-MM-DD)',
    meetings: 'Encontros',
    liturgical: 'Datas litúrgicas',
  },
  announcements: {
    title: 'Comunicados',
    emptyTitle: 'Sem comunicados',
    emptyBody: 'Os avisos pastorais aparecem aqui.',
    acknowledge: 'Confirmar leitura',
    acknowledged: 'Lido',
  },
  groups: {
    title: 'Grupos',
    emptyTitle: 'Sem grupos',
    emptyBody: 'Grupos pastorais da paróquia e da plataforma.',
    join: 'Entrar',
    leave: 'Sair',
    mine: 'Os meus',
    all: 'Todos',
    notice: 'Aviso do grupo',
    postNotice: 'Publicar aviso',
    noticePlaceholder: 'Escreva um aviso…',
  },
  catalog: {
    empty: 'Nada para mostrar neste espaço.',
    error: 'Não foi possível carregar.',
    open: 'Abrir',
    search: 'Pesquisar',
    categories: 'Categorias',
  },
  settings: {
    title: 'Configurações',
    profile: 'Os seus dados',
    password: 'Alterar senha',
    currentPassword: 'Senha atual',
    newPassword: 'Nova senha',
    emailPrefs: 'E-mails',
    saved: 'Guardado',
    consents: 'Consentimentos',
    granted: 'Autorizado',
    denied: 'Não autorizado',
    twoFactor: 'Verificação em dois passos',
    twoFactorStart: 'Ativar 2FA',
    twoFactorConfirm: 'Confirmar código',
    twoFactorDisable: 'Desativar 2FA',
    twoFactorSecret: 'Chave para o autenticador',
    twoFactorEnabled: 'Ativo neste telemóvel',
    twoFactorOff: 'Ainda não está ativo',
  },
  birthdays: {
    title: 'Aniversários',
    empty: 'Sem aniversários próximos.',
  },
} as const;

export const ATTENDANCE_STATUSES = ['PRESENT', 'ABSENT', 'LATE', 'EXCUSED'] as const;
export type AttendanceStatus = (typeof ATTENDANCE_STATUSES)[number];
